rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby
  - rbx
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/rails-3.1
  - gemfiles/rails-3.2
  - gemfiles/rails-4.0

env:
  - DEBUG=1

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx
    - rvm: 1.9.3

